#Publish to NuGet (runs on tagged pushes like v1.0.0)

name: Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*' # e.g. v0.2.0, v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Pack
      run: dotnet pack src/Tiptap.Core/Tiptap.Core.csproj -c Release -o out /p:Version=${GITHUB_REF#refs/tags/v}

    - name: Publish to NuGet
      run: dotnet nuget push "out/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
    
    - name: Publish to GitHub Packages
      run: dotnet nuget push "out/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate
